#-----=====[ Format Item Set ]=====-----#

#<itemset_id>:
#  Name: <itemset_name>
#  Bonus:
#    <amount_1>:
#      Description:
#      - "<desc_1>"
#      - "<desc_2>"
#      Effect:
#        Stats:
#          <effect_stats_1>: <value>
#          <effect_stats_2>: <value>
#        Ability_Weapon:
#          <ability_weapon_1>:
#            Chance: <value>
#            Grade: <value>
#  Component:
#    <component_key>:
#      KeyLore: <keylore>
#      Display_Name: <display_name>
#      Material: <material>
#      Data: <data>
#      Shiny: <shiny>
#      Unbreakable: <unbreakable>
#      Enchantment:
#        <enchantment_1>: <value>
#        <enchantment_2>: <value>
#      Slots:
#      - "<slot_1>"
#      - "<slot_2>"
#      Flags:
#      - "<flag_1>"
#      - "<flag_2>"
#      Lores:
#      - "<lore_1>"
#      - "<lore_2>"
#
#note: ItemComponentID = <itemset_id> + "_" + <component_key>

#-----=====[ Item Flags ]=====-----#

#HIDE_ENCHANTS
#HIDE_ATTRIBUTES
#HIDE_UNBREAKABLE
#HIDE_DESTROYS
#HIDE_PLACED_ON
#HIDE_POTION_EFFECTS

#-----=====[ Bonus Effect Stats ]=====-----#

#Additional_Damage: Bonus additional damage.
#Percent_Damage: Bonus percent damage based on damage.
#Penetration: Bonus penetration to ignore enemy armor.
#PvP_Damage: Bonus percent damage when attack Player.
#PvE_Damage: Bonus percent damage when attack Non-Player.
#Additional_Defense: Bonus additional defense.
#Percent_Defense: Bonus percent defense based on defense.
#Max_Health: Bonus max health when wearing armor.
#PvP_Defense: Bonus percent defense when attacked by Player.
#PvE_Defense: Bonus percent defense when attacked by Non-Player.
#Critical_Chance: Add chance of critical hit.
#Critical_Damage: Add critical damage in percent.
#Block_Amount: Add amount value of block damage.
#Block_Rate: Add chance of block in percent.
#Hit_Rate: Add chance of hit rate in percent.
#Dodge_Rate: Add chance of dodge in percent.

#-----=====[ Global Placeholder ]=====-----#

#{myitems_text_lorestats:<lorestats>:<min value>:[<max value>]}
#{myitems_text_ability:<ability>:<grade>:<chance>}
#{myitems_text_buff:<buff>:<grade>}
#{myitems_text_power:<power>:<click>:<type>:[<cooldown>]}
#{myitems_text_socket_empty}
#{myitems_text_socket_fill:<gems>}
#{myitems_text_element:<element>:<value>}
#{myitems_text_requirement_Unbound}
#{myitems_text_requirement_Bound:<player>}
#{myitems_text_requirement_Level:<level>}
#{myitems_text_requirement_Permission:<permission>}
#{myitems_text_requirement_Class:<class>}

#note: use "~" for range value

#-----=====[ Item Set Configuration ]=====-----#

Crimson_Flame:
  Name: "Crimson Flame"
  Bonus:
    2:
      Description:
      - "Damage +4"
      - "Critical Chance +5%"
      Effect:
        Stats:
          Additional_Damage: 4.0
          Critical_Chance: 5.0
    3:
      Description:
      - "Defense +7.2"
      Effect:
        Stats:
          Additional_Defense: 7.2
    4:
      Description:
      - "Block Rate +10%"
      Effect:
        Stats:
          Block_Rate: 10
    5:
      Description:
      - "Chance of 25% to apply Flame Wheel V"
      Effect:
        Ability_Weapon:
          Flame_Wheel:
            Chance: 25
            Grade: 5
  Component:
    Sword:
      KeyLore: "Crimson Flame Sword"
      Display_Name: "&8&l[ &cCrimson Flame Sword &8&l]"
      Material: "Iron_Sword"
      Slots:
      - "MainHand"
      Flags:
      - "HIDE_ATTRIBUTES"
      Lores:
      - "&8&l&m==========&r&8&l[&r &2&lDesc&r &8&l]&r&8&l&m=========="
      - "&2A sword forged using a fire dragon's soul"
      - "&7Tier: &6Legendary"
      - "&8&l&m==========&r&8&l[&r &2&lStatus&r &8&l]&r&8&l&m=========="
      - "{myitems_text_lorestats:damage:12~15:20~24}"
      - "{myitems_text_lorestats:critical_chance:10~15}"
      - "{myitems_text_lorestats:critical_damage:1.5~1.8}"
      - "{myitems_text_lorestats:durability:1~2048:2048}"
      - "&8&l&m==========&r&8&l[&r &2&lBuff&r &8&l]&r&8&l&m=========="
      - "{myitems_text_buff:jump:1~3}"
      - "{myitems_text_buff:luck:1~5}"
      - "&8&l&m==========&r&8&l[&r &2&lSocket&r &8&l]&r&8&l&m=========="
      - "{myitems_text_socket_empty}"
      - "{myitems_text_socket_empty}"
      - "{myitems_text_socket_empty}"
    Bow:
      KeyLore: "Crimson Flame Bow"
      Display_Name: "&8&l[ &cCrimson Flame Bow &8&l]"
      Material: "Bow"
      Slots:
      - "MainHand"
      Flags:
      - "HIDE_ATTRIBUTES"
      Lores:
      - "&8&l&m==========&r&8&l[&r &2&lDesc&r &8&l]&r&8&l&m=========="
      - "&2A bow crafted using a fire dragon's soul"
      - "&7Tier: &6Legendary"
      - "&8&l&m==========&r&8&l[&r &2&lStatus&r &8&l]&r&8&l&m=========="
      - "{myitems_text_lorestats:damage:8~12:16~20}"
      - "{myitems_text_lorestats:critical_chance:15~20}"
      - "{myitems_text_lorestats:critical_damage:1.5~1.8}"
      - "{myitems_text_lorestats:durability:1~2048:2048}"
      - "&8&l&m==========&r&8&l[&r &2&lBuff&r &8&l]&r&8&l&m=========="
      - "{myitems_text_buff:jump:1~3}"
      - "{myitems_text_buff:luck:1~5}"
      - "&8&l&m==========&r&8&l[&r &2&lSocket&r &8&l]&r&8&l&m=========="
      - "{myitems_text_socket_empty}"
      - "{myitems_text_socket_empty}"
      - "{myitems_text_socket_empty}"
    Helmet:
      KeyLore: "Crimson Flame Helmet"
      Display_Name: "&8&l[ &cCrimson Flame Helmet &8&l]"
      Material: "Iron_Helmet"
      Slots:
      - "Helmet"
      Flags:
      - "HIDE_ATTRIBUTES"
      Lores:
      - "&8&l&m==========&r&8&l[&r &2&lDesc&r &8&l]&r&8&l&m=========="
      - "&2A helmet forged using a fire dragon's soul"
      - "&7Tier: &6Legendary"
      - "&8&l&m==========&r&8&l[&r &2&lStatus&r &8&l]&r&8&l&m=========="
      - "{myitems_text_lorestats:defense:4~7}"
      - "{myitems_text_lorestats:block_rate:2~3.2}"
      - "{myitems_text_lorestats:block_amount:2.5~5}"
      - "{myitems_text_lorestats:durability:1~2048:2048}"  
      - "&8&l&m==========&r&8&l[&r &2&lSocket&r &8&l]&r&8&l&m=========="
      - "{myitems_text_socket_empty}"
      - "{myitems_text_socket_empty}"
      - "{myitems_text_socket_empty}"
    Chestplate:
      KeyLore: "Crimson Flame Chestplate"
      Display_Name: "&8&l[ &cCrimson Flame Chestplate &8&l]"
      Material: "Iron_Chestplate"
      Slots:
      - "Chestplate"
      Flags:
      - "HIDE_ATTRIBUTES"
      Lores:
      - "&8&l&m==========&r&8&l[&r &2&lDesc&r &8&l]&r&8&l&m=========="
      - "&2A chestplate forged using a fire dragon's soul"
      - "&7Tier: &6Legendary"
      - "&8&l&m==========&r&8&l[&r &2&lStatus&r &8&l]&r&8&l&m=========="
      - "{myitems_text_lorestats:defense:7~11}"
      - "{myitems_text_lorestats:block_rate:3~4}"
      - "{myitems_text_lorestats:block_amount:3~6}"
      - "{myitems_text_lorestats:durability:1~2048:2048}"
      - "&8&l&m==========&r&8&l[&r &2&lSocket&r &8&l]&r&8&l&m=========="
      - "{myitems_text_socket_empty}"
      - "{myitems_text_socket_empty}"
      - "{myitems_text_socket_empty}"
    Leggings:
      KeyLore: "Crimson Flame Leggings"
      Display_Name: "&8&l[ &cCrimson Flame Leggings &8&l]"
      Material: "Iron_Leggings"
      Slots:
      - "Leggings"
      Flags:
      - "HIDE_ATTRIBUTES"
      Lores:
      - "&8&l&m==========&r&8&l[&r &2&lDesc&r &8&l]&r&8&l&m=========="
      - "&2A leggings forged using a fire dragon's soul"
      - "&7Tier: &6Legendary"
      - "&8&l&m==========&r&8&l[&r &2&lStatus&r &8&l]&r&8&l&m=========="
      - "{myitems_text_lorestats:defense:5~7}"
      - "{myitems_text_lorestats:block_rate:2~3}"
      - "{myitems_text_lorestats:block_amount:2~4}"
      - "{myitems_text_lorestats:durability:1~2048:2048}"
      - "&8&l&m==========&r&8&l[&r &2&lSocket&r &8&l]&r&8&l&m=========="
      - "{myitems_text_socket_empty}"
      - "{myitems_text_socket_empty}"
      - "{myitems_text_socket_empty}"
    Boots:
      KeyLore: "Crimson Flame Boots"
      Display_Name: "&8&l[ &cCrimson Flame Boots &8&l]"
      Material: "Iron_Boots"
      Slots:
      - "Boots"
      Flags:
      - "HIDE_ATTRIBUTES"
      Lores:
      - "&8&l&m==========&r&8&l[&r &2&lDesc&r &8&l]&r&8&l&m=========="
      - "&2A boots forged using a fire dragon's soul"
      - "&7Tier: &6Legendary"
      - "&8&l&m==========&r&8&l[&r &2&lStatus&r &8&l]&r&8&l&m=========="
      - "{myitems_text_lorestats:defense:3~5}"
      - "{myitems_text_lorestats:block_rate:2.5~4}"
      - "{myitems_text_lorestats:block_amount:2.5~5}"
      - "{myitems_text_lorestats:durability:1~2048:2048}"
      - "&8&l&m==========&r&8&l[&r &2&lSocket&r &8&l]&r&8&l&m=========="
      - "{myitems_text_socket_empty}"
      - "{myitems_text_socket_empty}"
      - "{myitems_text_socket_empty}"